name: google_mlkit_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11
  google_mlkit_text_recognition: ^0.5.0
  hooks_riverpod: ^2.1.3
  flutter_native_image: ^0.0.6+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:

  uses-material-design: true
